# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10f7185f16d5005c63411fb85f2a185f00088d5fceccebc06b1e2d384ebb313e423a5845c15dda87706ef50ba5b88eda059b95e2bd324ab680e95d7ecc33dc8b

test:
  secret_key_base: ad7b7a4d5e2486022e69c5dc0becc9f85024e2db3b4b0c9474d066d54a73bfbffb1b899666169382fc0952de4b4ea2dbf9d536936c6c6e9cae37a26edb1898ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
