# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3957c5323f7101cafb4c4b0cc928527a0d82f2526bbd78c4bbc073f71c1489545a91cf898af784e9ecc9e2fbb96db280def4ee763f4005d5646de07a127d7bd8

test:
  secret_key_base: 287ca631f33951c44016bdf7c958bcba7f4103be6a98b793aec309598abee73403610ebc04481dae99b711550f1e42075d3a50efa2914a7eca7c4b3e775c4fe5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
